services:
  localstack:
    image: localstack/localstack:stable
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb

  cache:
    image: valkey/valkey:9-alpine
    ports:
      - "6379:6379"
